Gracefully handle missing module when instrumenting import dependency
Fixes an issue where build throws unhandled exception while instrumenting import dependency of a missing module that does not include any clear description of what caused it.

Before:
```
/uber/fusionjs/.yarn/$$virtual/fusion-cli-virtual-c219a1713c/1/public/fusion-cli/bin/cli-runner.js:12
  throw e;
  ^

TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at ChunkGraph._getChunkGraphModule (/uber/fusionjs/.yarn/$$virtual/webpack-virtual-2ac792728e/0/cache/webpack-npm-5.44.0-0560d0cac0-541ee0607b.zip/node_modules/webpack/lib/ChunkGraph.js:257:18)
    at ChunkGraph.getModuleId (/uber/fusionjs/.yarn/$$virtual/webpack-virtual-2ac792728e/0/cache/webpack-npm-5.44.0-0560d0cac0-541ee0607b.zip/node_modules/webpack/lib/ChunkGraph.js:1177:20)
    at /uber/fusionjs/.yarn/$$virtual/fusion-cli-virtual-c219a1713c/1/public/fusion-cli/build/plugins/instrumented-import-dependency-template-plugin.js:235:46
    at Array.forEach (<anonymous>)
    ...
```
After:
```
error: client: ./src/main.js 5:14-43
Module not found: Error: Can't resolve './missing-module.js' in '/uber/fusionjs/public/fusion-cli-tests/test/e2e/missing-module/fixture/src'
resolve './missing-module.js' in '/uber/fusionjs/public/fusion-cli-tests/test/e2e/missing-module/fixture/src'
   ...
error: server: ./src/main.js 5:14-43
Module not found: Error: Can't resolve './missing-module.js' in '/uber/fusionjs/public/fusion-cli-tests/test/e2e/missing-module/fixture/src'
resolve './missing-module.js' in '/uber/fusionjs/public/fusion-cli-tests/test/e2e/missing-module/fixture/src'
   ...

error: Compiler stats included errors.
    at /uber/fusionjs/.yarn/$$virtual/fusion-cli-virtual-c219a1713c/1/public/fusion-cli/commands/build.js:78:30
```